# Generated by Django 3.2.20 on 2023-08-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_seats_first_class', models.PositiveIntegerField()),
                ('total_seats_second_class', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin_class', models.CharField(max_length=20)),
                ('seat_numbers', models.CharField(max_length=100)),
                ('reservation_id', models.CharField(max_length=10, unique=True)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.train')),
            ],
        ),
    ]
